# Generated by Django 4.1 on 2022-08-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='urunler/', verbose_name='Ürün Resmi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=200, verbose_name='Ürün İsmi'),
        ),
    ]
